#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

echo "═══════════════════════════════════════════════════════════"
echo "v41 — FIX VERO: R2 CORS + race condition + Done button"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "ROOT CAUSE TROVATA (e' un bug di CORS, non di salvataggio):"
echo ""
echo "  Cloudflare R2 con custom domain (assets.perenne.app) NON"
echo "  manda di default gli header CORS (Access-Control-Allow-Origin)."
echo ""
echo "  L'editor usa fabricLib.Image.fromURL(url, ..., {crossOrigin:"
echo "  'anonymous'}) per i loghi salvati. Il browser fa una richiesta"
echo "  CORS-preflight verso R2, R2 risponde senza Access-Control-*,"
echo "  il browser blocca silenziosamente. fabric.Image risulta con"
echo "  width=0 e NON appare sul canvas, ma compare nel sidebar"
echo "  (perche' lo state React e' popolato lo stesso)."
echo ""
echo "  Tu vedi: 'logo nel sidebar ma non sul canvas' = sembra sparito."
echo "  Cliccando Save di nuovo, salvi con coordinate NaN/0 e poi i"
echo "  dati si corrompono davvero."
echo ""
echo "  Le miniature in /designs invece usano <img src='...'> SENZA"
echo "  crossOrigin -> R2 risponde normalmente -> funzionano. Ma"
echo "  v37/v39 thumbnail erano ancora in fase di rollout, quindi"
echo "  vedevi la cover beige/default a causa di altre cause."
echo ""
echo "FIX in v41:"
echo "  1. Editor (Cover + Page) — loadAssetFromUrl ora prova prima"
echo "     con crossOrigin:anonymous, e se l'immagine ritorna 0x0"
echo "     fa retry SENZA crossOrigin. L'immagine si vede sul canvas"
echo "     (filtri non funzionano su immagini non-CORS, ma almeno"
echo "     non spariscono)."
echo "  2. Banner di errore visibile: quando un caricamento fallisce,"
echo "     compare un banner ambra in cima all'editor con i nomi"
echo "     dei file. Niente piu' sparizioni silenziose."
echo "  3. buildConfig + buildWatermarks: ora SCARTA esplicitamente"
echo "     asset con coordinate NaN o senza url+dataUrl, con log"
echo "     in console. Non puoi piu' salvare dati corrotti."
echo "  4. Race fix: quando R2 upload finisce prima che fromURL"
echo "     callback abbia aggiunto l'entry, il setAssets retry-loop"
echo "     riprova fino a 10 volte (1s totale)."
echo "  5. Pulsante 'Done →' prominente nel header dell'edit page,"
echo "     accanto al badge Default."
echo "  6. Endpoint diagnostico GET /api/diagnostics/design/[id] che"
echo "     mostra cosa c'e' davvero nel DB (utile per debug)."
echo ""
echo "AZIONE MANUALE RICHIESTA per fix definitivo CORS:"
echo "  Vai su Cloudflare dashboard:"
echo "    R2 -> perenne-assets -> Settings -> CORS Policy -> Add"
echo "    AllowedOrigins: https://business.perenne.app, http://localhost:3000"
echo "    AllowedMethods: GET"
echo "    AllowedHeaders: *"
echo "    MaxAgeSeconds: 3600"
echo "  Poi: R2 -> perenne-assets -> Settings -> Public access ->"
echo "    custom domain assets.perenne.app -> Purge cache"
echo ""
echo "  Dopo aver fatto questo, i filtri di Fabric (invert color)"
echo "  funzioneranno perfettamente sui loghi salvati. Senza il"
echo "  fix CORS, i loghi appaiono ma invert non funziona."
echo ""
echo "Premi INVIO per continuare, Ctrl+C per annullare."
read -r _

echo "═══════════════════════════════════════════════════════════"
echo "STEP 1/2: copia file"
echo "═══════════════════════════════════════════════════════════"
mkdir -p components/editor
mkdir -p app/api/diagnostics/design/\[id\]
mkdir -p app/designs/\[id\]/edit

cp -v _v41_payload/components/editor/CoverEditor.tsx components/editor/CoverEditor.tsx
cp -v _v41_payload/components/editor/PageEditor.tsx components/editor/PageEditor.tsx
cp -v "_v41_payload/app/api/diagnostics/design/[id]/route.ts" "app/api/diagnostics/design/[id]/route.ts"
cp -v "_v41_payload/app/designs/[id]/edit/page.tsx" "app/designs/[id]/edit/page.tsx"

rm -rf _v41_payload

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 2/2: git commit + push"
echo "═══════════════════════════════════════════════════════════"
git add -A
git commit -m "v41: R2 CORS fallback + race fix + Done button + diagnostic endpoint"
git push

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "FATTO!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Test post-deploy + HARD-REFRESH (Cmd+Shift+R):"
echo ""
echo "1. Vai a un design esistente (quello dove avevi caricato loghi)."
echo "   Apri /api/diagnostics/design/IL_TUO_DESIGN_ID per VEDERE cosa"
echo "   c'e' davvero nel DB (incolla l'URL nel browser, dovrai esser"
echo "   loggato). Mandami quel JSON. Cosi' sappiamo se il save e'"
echo "   effettivamente avvenuto in passato."
echo ""
echo "2. Editor: i loghi DEVONO apparire ora sul canvas (anche se R2"
echo "   non ha CORS ancora). Eventualmente con un banner ambra in"
echo "   alto se almeno uno aveva fallito."
echo ""
echo "3. Click 'Done ->' in alto a destra per uscire."
echo ""
echo "4. /designs: i thumbnail mostrano colore + logo come saved."
echo ""
echo "5. Configura CORS su R2 (vedi sopra). Dopo, anche l'invert"
echo "   funzionera' sui loghi salvati (oltre che sui nuovi)."
echo ""
