#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

echo "═══════════════════════════════════════════════════════════"
echo "v45 — Late-binding Design ↔ Batch (UI + API)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Include v44 + v45:"
echo ""
echo "  v44 (server fix):"
echo "    POST /api/team/[code]/redeem ora legge il design da:"
echo "      1. NotebookCode.designId (link diretto del batch)"
echo "      2. Order.designSnapshotJson (codici Stripe)"
echo "      3. Order.design (fallback)"
echo "    Senza v44 i batch admin con designId ignorato → design null."
echo ""
echo "  v45 (UI + API per associazione tardiva):"
echo "    - POST /api/admin/codes/assign-design (per code o per batch)"
echo "    - Pagina /admin/codes ora mostra il design come picker"
echo "      cliccabile inline, non piu' come testo statico."
echo "      Click sul nome del design → dropdown con tutti i design"
echo "      della company → seleziona → salva → la pagina si"
echo "      ricarica con il nuovo legame."
echo ""
echo "Flusso ora supportato:"
echo "  1. Cliente compra batch (designId opzionale, di solito vuoto)"
echo "  2. Tu lavori sul design con lui"
echo "  3. Quando il design e' pronto, vai su /admin/codes,"
echo "     clicchi 'no design — click to assign' sulla riga del batch,"
echo "     scegli il design dalla lista, fatto."
echo "  4. iPad gia' attivati: al prossimo refresh prendono il nuovo"
echo "     design (vedi iOS v3 — refresh-on-launch)."
echo ""
echo "Premi INVIO per continuare, Ctrl+C per annullare."
read -r _

echo "═══════════════════════════════════════════════════════════"
echo "STEP 1/2: copia file"
echo "═══════════════════════════════════════════════════════════"
mkdir -p "app/api/team/[code]/redeem"
mkdir -p "app/api/admin/codes/assign-design"
mkdir -p "app/admin/codes"
mkdir -p "components/admin"

cp -v "_v45_payload/app/api/team/[code]/redeem/route.ts" "app/api/team/[code]/redeem/route.ts"
cp -v "_v45_payload/app/api/admin/codes/assign-design/route.ts" "app/api/admin/codes/assign-design/route.ts"
cp -v "_v45_payload/app/admin/codes/page.tsx" "app/admin/codes/page.tsx"
cp -v "_v45_payload/components/admin/BatchDesignPicker.tsx" "components/admin/BatchDesignPicker.tsx"

rm -rf _v45_payload

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 2/2: git commit + push"
echo "═══════════════════════════════════════════════════════════"
git add -A
git commit -m "v44+v45: late-binding design assignment for code batches (server + UI)"
git push

echo ""
echo "FATTO. Aspetta deploy verde su Vercel."
echo ""
echo "Test workflow:"
echo "  1. Vai su /admin/codes"
echo "  2. Trova il batch 'stelvio collection May 2026'"
echo "  3. Nella colonna Design dovresti vedere 'no design — click to assign'"
echo "  4. Click → dropdown con i design Stelvio → seleziona"
echo "  5. La pagina si ricarica e ora la cella mostra il nome del design"
echo ""
echo "Verifica via curl che il redeem ritorni il design (resetta prima"
echo "PRN-AZKP-32PJ ad AVAILABLE da Neon SQL):"
echo ""
echo "  curl -i -X POST 'https://business.perenne.app/api/team/PRN-AZKP-32PJ/redeem' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"deviceId\":\"test\"}' --max-time 30"
echo ""
echo "Risposta deve avere design.snapshot.assets[] non vuoto."
