#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

echo "═══════════════════════════════════════════════════════════"
echo "v47 — Customer-side batch management + admin company logo upload"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Cosa fa:"
echo ""
echo "  1. /codes (cliente) ora e' una GRID di batch"
echo "     - Una card per ogni batch acquistato"
echo "     - Mostra: batch label, design (o 'no design'),"
echo "       totale codici, available/claimed"
echo "     - Click sulla card → detail page del batch"
echo ""
echo "  2. /codes/[batchLabel] (NUOVA pagina)"
echo "     - Detail page del batch"
echo "     - Selettore design inline (BatchDesignPicker)"
echo "       il cliente OWNER/ADMIN puo' associare/cambiare design"
echo "     - Tabella di tutti i codici del batch"
echo ""
echo "  3. /api/admin/codes/assign-design AGGIORNATA"
echo "     - Prima SUPERADMIN-only, ora OWNER/ADMIN della company"
echo "       possono modificare i loro batch"
echo "     - Company scope verificato server-side"
echo ""
echo "  4. /admin/companies/[id] (rebuilt)"
echo "     - Stats company + brand assets + info"
echo "     - URL inputs sostituiti con uploaders veri"
echo "       (PNG, JPEG, SVG, WebP, max 5MB)"
echo ""
echo "  5. /api/admin/companies/[id]/logo (NUOVA)"
echo "     - Upload R2 da admin side, SUPERADMIN only"
echo ""
echo "Premi INVIO per continuare, Ctrl+C per annullare."
read -r _

echo "═══════════════════════════════════════════════════════════"
echo "STEP 1/2: copia file"
echo "═══════════════════════════════════════════════════════════"

# Copy with their full directory paths preserved
mkdir -p "app/codes/[batchLabel]"
mkdir -p "app/admin/companies/[id]"
mkdir -p "app/api/admin/companies/[id]/logo"
mkdir -p "app/api/admin/codes/assign-design"
mkdir -p "components/admin"

cp -v "_v47_payload/app/codes/page.tsx" "app/codes/page.tsx"
cp -v "_v47_payload/app/codes/[batchLabel]/page.tsx" "app/codes/[batchLabel]/page.tsx"
cp -v "_v47_payload/app/admin/companies/[id]/page.tsx" "app/admin/companies/[id]/page.tsx"
cp -v "_v47_payload/app/api/admin/companies/[id]/logo/route.ts" "app/api/admin/companies/[id]/logo/route.ts"
cp -v "_v47_payload/app/api/admin/codes/assign-design/route.ts" "app/api/admin/codes/assign-design/route.ts"
cp -v "_v47_payload/components/admin/CompanyLogoUploaders.tsx" "components/admin/CompanyLogoUploaders.tsx"

rm -rf _v47_payload

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 2/2: git commit + push"
echo "═══════════════════════════════════════════════════════════"
git add -A
git commit -m "v47: customer batch management UI + admin company logo upload"
git push

echo ""
echo "FATTO. Aspetta deploy verde su Vercel."
echo ""
echo "Test workflow CLIENTE:"
echo "  1. Login come OWNER della company Stelvio"
echo "  2. Sidebar → Codes"
echo "  3. Vedi grid con 1 card 'stelvio collection May 2026'"
echo "     scritto 'no design' (giusto, non e' associato)"
echo "  4. Click sulla card → entri nel detail"
echo "  5. Click sul selettore design → seleziona Stelvio"
echo "  6. Banner conferma, lista codici sotto"
echo ""
echo "Test workflow ADMIN:"
echo "  1. Login come SUPERADMIN"
echo "  2. Sidebar → Companies → click su stelvio collection"
echo "  3. Vedi sezione 'Brand assets' con uploader"
echo "  4. Click 'Upload' su Symbol logo → seleziona PNG → carica"
echo "  5. Preview aggiornata, sidebar mostra il logo"
